name: HotbarSwitcher
version: 1.0
main: fr.skybeastmc.hotbarswitcher.Main
description: HotbarSwitcher
author: [SkyBeast55]
depend: [ProtocolLib]
commands:
  switch:
    description: Switch your hotbar
    alias: [s]
    permission: hotbar.switch
permissions:
  hotbar.item:
    default: op
  hotbar.switch:
    default: op